force-app/main/default/objects/Boat__c.object
<CustomObject>
    <fields>
        <fullName>BoatType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boat Type</label>
        <referenceTo>BoatType__c</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <inlineHelpText>In feet</inlineHelpText>
        <label>Length</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>Estimated Pric</inlineHelpText>
        <label>Price</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <label>Year Built</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BoatType__c.object
<CustomObject>
    <label>Boat Type</label>
    <nameField>
        <label>Boat Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BoatSearchResults.cls
public with sharing class BoatSearchResults {
    @AuraEnabled
    public static List<Boat__c> getBoats(String boatTypeId) {

        String query = String.join(new List<String>{
                'SELECT Id, Name, BoatType__c, Picture__c, Price__c, Length__c, Year_Built__c, Geolocation__Latitude__s, Geolocation__Longitude__s',
                'FROM Boat__c'
        }, ' ');

        if(boatTypeId != null && !String.isEmpty(boatTypeId)) {
            query = query + ' WHERE BoatType__c = \'' + boatTypeId + '\'';
        }

        return Database.query(query);

    }
}