force-app/main/default/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceCredentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Username and password credentials for external services</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for the external service</description>
        <label>Password</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>User for the external service</description>
        <label>Username</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ServiceCredentials</label>
</CustomObject>

out/production/My Development Org/objects/User.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BillingCalloutServiceTest.cls
@isTest
private class BillingCalloutServiceTest {
    public static User TEST_USER {
        get {
            User usr = [
                    SELECT Id
                    FROM User
                    WHERE Username = 'test.tester@weare4c.com.otapc'
            ];
            return usr;
        }
    }

    @TestSetup
    public static void setup() {
        Profile profile = [
                Select Id
                From Profile
                Where Name = 'System Administrator'
        ];

        User testUser = new User(
                FirstName = 'Testy',
                Alias = 'Tester',
                Email = 'Testy.Tester@test.domain',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Tester',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = profile.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'test.tester@weare4c.com.otapc'
        );

        insert testUser;

        Schema.DescribeSObjectResult schemaOpp = Schema.SObjectType.Opportunity;
        Map<Id, Schema.RecordTypeInfo> rtMapById = schemaOpp.getRecordTypeInfosById();
        List<Id> oppRecordsIds = new List<Id>(rtMapById.keySet());

        Account account = new Account(
                Name = 'Test Account'
        );

        insert account;

        Opportunity opportunity = new Opportunity(
                Name = 'Test Opp',
                Type = 'New Project',
                StageName = 'Qualification',
                RecordTypeId = oppRecordsIds.get(0),
                CloseDate = System.today(),
                Amount = 6436,
                AccountId = account.Id
        );

        insert opportunity;

        Project__c project = new Project__c(
                Name = 'Test Project',
                Opportunity__c = opportunity.Id,
                Start_Date__c = System.today(),
                End_Date__c = System.today().addMonths(2),
                Billable_Amount__c = 4325,
                Status__c = 'Running',
                ProjectRef__c = '03267bd7-b10e-42a4-9906-db51e3f7a159'
        );

        insert project;

        ServiceCredentials__c serviceCredentials = new ServiceCredentials__c();
        serviceCredentials.Username__c = 'pmsUser1';
        serviceCredentials.Password__c = 'pmsPass1';
        serviceCredentials.Name = 'BillingServiceCredential';
        insert serviceCredentials;
    }

    @IsTest
    public static void successBillToProjectTest() {
        System.runAs(TEST_USER) {
            Project__c project = queryProject();

            System.Test.startTest();
            Test.setMock(WebServiceMock.class, new BillingCalloutServiceMock());
            project.Status__c = 'Billable';
            update project;
            System.Test.stopTest();

            project = queryProject();
            System.assertEquals('Billed', project.Status__c);

        }
    }

    @IsTest
    public static void failureBillToProjectTest() {
        System.runAs(TEST_USER) {
            Project__c project = queryProject();

            System.Test.startTest();
            Test.setMock(WebServiceMock.class, new BillingCalloutServiceMockFailure());
            project.Status__c = 'Billable';
            update project;
            System.Test.stopTest();

            project = queryProject();
            System.assertEquals('Billable', project.Status__c);

        }
    }

    public static Project__c queryProject() {
        return [
                SELECT Id, Name, Status__c, Billable_Amount__c, ProjectRef__c
                FROM Project__c
                WHERE Name = 'Test Project'
        ];
    }

    public static Opportunity queryOpportunity() {
        return [
                SELECT Id, Name, StageName, CloseDate, Amount, Account.Name
                FROM Opportunity
                WHERE Name = 'Test Opp'
        ];
    }
}