force-app/main/default/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceCredentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Username and password credentials for external services</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password for the external service</description>
        <label>Password</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>User for the external service</description>
        <label>Username</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ServiceCredentials</label>
</CustomObject>

force-app/main/default/classes/BillingCalloutService.cls
public with sharing class BillingCalloutService{
    private static Set<String> projectFieldsNames;

    public static void callBillingService(List<Project__c> newList, Map<Id, Project__c> newMap, List<Project__c> oldList, Map<Id, Project__c> oldMap) {
        List<Project__c> projects = newList;
        List<Project__c> projectsToUpdate = new List<Project__c>();
        for (Project__c newProject : projects) {
            if('Billable'.equalsIgnoreCase(newProject.Status__c) && newProject.Status__c != oldMap.get(newProject.Id).Status__c) {
                ServiceCredentials__c credentials = ServiceCredentials__c.getInstance('BillingServiceCredential');
                billToProject(newProject.ProjectRef__c, newProject.Billable_Amount__c, credentials.Username__c, credentials.Password__c, newProject.Id);
            }
        }
    }

    @future(callout=true)
    public static void billToProject(String projectRef, Decimal billAmount, String username, String password, String projectId) {
        BillingServiceProxy billingServiceProxy = new BillingServiceProxy();

        BillingServiceProxy.project project = new BillingServiceProxy.project();
        project.username = username;
        project.password = password;
        project.projectid = projectId;
        project.billAmount = billAmount;
        project.projectRef = projectRef;

        BillingServiceProxy.InvoicesPortSoap11 invoicesPortSoap11 = new BillingServiceProxy.InvoicesPortSoap11();
        String response = invoicesPortSoap11.billProject(project);
        List<Project__c> projects = new List<Project__c>();
        if (response.equalsIgnoreCase('ok')) {
            projects = [
                    Select Id, Status__c
                    From Project__c
                    Where ProjectRef__c = :projectRef
            ];
            if(!projects.isEmpty()) {
                projects[0].Status__c = 'Billed';
                update projects;
            }
        }
    }
}