src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLAExpirationDate__c</fullName>
        <label>SLA Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountHandler.cls
/**
 * Created by Lenovo on 19.04.2017.
 */

public with sharing class AccountHandler {

    public static Account insertNewAccount(String accountName) {
        Account account = new Account(
                Name = accountName,
                Active__c = 'Yes',
                SLAExpirationDate__c = Date.newInstance(2017, 4, 22),
                SLA__c = 'Gold',
                SLASerialNumber__c = '43643'
        );

        try{
            insert account;
        }catch(DmlException e) {
            return null;
        }

        account = [
          SELECT
                  Id,
                  Name
          FROM Account
          WHERE Name = :accountName
        ];

        return account;
    }


}