src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLAExpirationDate__c</fullName>
        <label>SLA Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AddPrimaryContactTest.cls
/**
 * Created by Lenovo on 19.04.2017.
 */

@IsTest
private class AddPrimaryContactTest {

    @TestSetup
    public static void setup() {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < 50; i++) {
            accounts.add(new Account(
                    BillingState = 'NY',
                    Name = 'TestAccount' + i,
                    Active__c = 'Yes',
                    SLAExpirationDate__c = Date.newInstance(2017, 4, 22),
                    SLA__c = 'Gold',
                    SLASerialNumber__c = '43643' + i
            ));
        }

        for (Integer i = 0; i < 50; i++) {
            accounts.add(new Account(
                    BillingState = 'CA',
                    Name = 'TestAccount' + i,
                    Active__c = 'Yes',
                    SLAExpirationDate__c = Date.newInstance(2017, 4, 22),
                    SLA__c = 'Gold',
                    SLASerialNumber__c = '44643' + i
            ));
        }

        insert accounts;

        Contact contact = new Contact(
                FirstName = 'TestFirstName',
                LastName = 'TestLastName'
        );

        insert contact;
    }

    @isTest
    public static void testAddPrimaryContactWhenBillingStateIsNY(){
        Contact contact = [
          SELECT
                  FirstName,
                  LastName,
                  AccountId
          FROM Contact
          LIMIT 1
        ];

        Test.startTest();
        AddPrimaryContact addPrimaryContact = new AddPrimaryContact(contact, 'NY');
        System.enqueueJob(addPrimaryContact);
        Test.stopTest();

        contact = [
                SELECT
                        FirstName,
                        LastName,
                        AccountId
                FROM Contact
                LIMIT 1
        ];


        List<Contact> contacts = [
                SELECT Id
                FROM Contact
                WHERE Account.BillingState = 'NY'
        ];

        List<Account> accounts = [
            SELECT Id
            FROM Account
            WHERE BillingState = 'NY'
        ];

        System.assertEquals(contacts.size(), accounts.size());
    }

    @isTest
    public static void testAddPrimaryContactWhenBillingStateIsCA(){
        Contact contact = [
                SELECT
                        FirstName,
                        LastName,
                        AccountId
                FROM Contact
                LIMIT 1
        ];

        Test.startTest();
        AddPrimaryContact addPrimaryContact = new AddPrimaryContact(contact, 'CA');
        System.enqueueJob(addPrimaryContact);
        Test.stopTest();

        contact = [
                SELECT
                        FirstName,
                        LastName,
                        AccountId
                FROM Contact
                LIMIT 1
        ];


        List<Contact> contacts = [
                SELECT Id
                FROM Contact
                WHERE Account.BillingState = 'CA'
        ];

        List<Account> accounts = [
                SELECT Id
                FROM Account
                WHERE BillingState = 'CA'
        ];

        System.assertEquals(contacts.size(), accounts.size());
    }
}