src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DeliveryInstallationStatus__c</fullName>
        <label>Delivery/Installation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Yet to begin</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <label>Billable Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectRESTService.cls
@RestResource(urlMapping = '/project/*')
global with sharing class ProjectRESTService {
    @HttpPost
    global static String postProjectData(
            String ProjectRef,
            String ProjectName,
            String OpportunityId,
            Date StartDate,
            Date EndDate,
            Double Amount,
            String Status
    ) {

        Savepoint sp;

        try {

            sp = Database.setSavepoint();
            List<Project__c> projects = queryProjectByExternalId(ProjectRef);
            for(Project__c project : projects) {
                project.Name = ProjectName;
                project.Start_Date__c = StartDate;
                project.End_Date__c = EndDate;
                project.Billable_Amount__c = Amount;
                project.Status__c = Status;
            }


            if(!projects.isEmpty()) {
                update projects;
            } else {
                insert new Project__c(
                        ProjectRef__c = ProjectRef,
                        Name = ProjectName,
                        Opportunity__c = OpportunityId,
                        Start_Date__c = StartDate,
                        End_Date__c = EndDate,
                        Billable_Amount__c = Amount,
                        Status__c = Status

                );
            }

            List<Opportunity> opportunities = queryOpportunities(OpportunityId);
            for(Opportunity opportunity : opportunities) {
                opportunity.DeliveryInstallationStatus__c = 'In Progress';
            }

            if(!opportunities.isEmpty()) {
                update opportunities;
            }

            System.debug('ProjectRef' + ProjectRef);
            System.debug('StartDate' + StartDate);
            System.debug('EndDate' + EndDate);
            System.debug('Amount' + Amount);
            System.debug('Status' + Status);

            return 'OK';
        } catch (Exception ex) {
            Database.rollback(sp);
            return ex.getMessage();
        }
    }

    public static List<Project__c> queryProjectByExternalId(String projectRef) {
        return [
                SELECT Id
                FROM Project__c
                WHERE ProjectRef__c = :projectRef
        ];
    }

    public static List<Opportunity> queryOpportunities(String opportunityId) {
        return [
                SELECT Id
                FROM Opportunity
                WHERE Id = :opportunityId
        ];
    }

}